//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Documentation = new HashSet<Documentation>();
            this.TTN = new HashSet<TTN>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDKey { get; set; }
        public Nullable<int> Contract_Number { get; set; }
        public Nullable<System.DateTime> Contract_Signing { get; set; }
        public string Object_name { get; set; }
        public string subject_of_contract { get; set; }
        public Nullable<decimal> Contract_amount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public string Project_Manager { get; set; }
        public Nullable<int> approval_list_id { get; set; }
        public Nullable<int> orders_Id { get; set; }
        public string Note { get; set; }
    
        public virtual Approval_List Approval_List { get; set; }
        public virtual Approval_List Approval_List1 { get; set; }
        public virtual Main_Reestr Main_Reestr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation> Documentation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTN> TTN { get; set; }
    }
}
