//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Main_Reestr = new HashSet<Main_Reestr>();
        }
    
        public int ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_UNP { get; set; }
        public string Customer_Adress { get; set; }
        public string Customer_contact { get; set; }
        public Nullable<int> Customer_code { get; set; }
        public Nullable<int> Type { get; set; }
        public string R_S { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Main_Reestr> Main_Reestr { get; set; }
    }
}
