//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public int ID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public string Document_Index { get; set; }
        public Nullable<System.DateTime> date_of_transfer_to_settlement_group { get; set; }
        public Nullable<System.DateTime> date_of_transfer_to_the_customer_for_approval { get; set; }
        public Nullable<System.DateTime> date_of_agreement_by_the_customer { get; set; }
        public Nullable<System.DateTime> date_of_submission_for_inspection { get; set; }
        public Nullable<System.DateTime> date_of_receipt_of_inspection { get; set; }
        public Nullable<System.DateTime> start_date_of_picking_and_purchasing { get; set; }
        public Nullable<System.DateTime> date_of_submission_of_documentation_to_MPO { get; set; }
        public Nullable<System.DateTime> date_of_transfer_for_picking_from_MPO { get; set; }
        public Nullable<System.DateTime> build_start_date { get; set; }
        public Nullable<System.DateTime> Operational_control { get; set; }
        public string Operational_control_result { get; set; }
        public Nullable<System.DateTime> Acceptance_control { get; set; }
        public string Acceptance_control_results { get; set; }
        public string Acceptance_control_protocol { get; set; }
        public Nullable<System.DateTime> Date_of_shipment { get; set; }
        public Nullable<int> Act_number { get; set; }
        public Nullable<System.DateTime> Act_Date { get; set; }
        public Nullable<System.DateTime> PSI { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
