//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Reestr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main_Reestr()
        {
            this.Tenders = new HashSet<Tenders>();
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Doc_Number { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Object_name { get; set; }
        public Nullable<int> general_contractor { get; set; }
        public Nullable<int> sub_contractor { get; set; }
        public string Link { get; set; }
        public string project_type { get; set; }
        public string stage { get; set; }
        public Nullable<int> resp_personID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Respons_persons Respons_persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenders> Tenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
    }
}
