//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectStDBEntities : DbContext
    {
        public ProjectStDBEntities()
            : base("name=ProjectStDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approval_List> Approval_List { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Documentation> Documentation { get; set; }
        public virtual DbSet<Main_Reestr> Main_Reestr { get; set; }
        public virtual DbSet<PersonStats> PersonStats { get; set; }
        public virtual DbSet<Respons_persons> Respons_persons { get; set; }
        public virtual DbSet<TTN> TTN { get; set; }
        public virtual DbSet<User_Types> User_Types { get; set; }
        public virtual DbSet<Users_DB> Users_DB { get; set; }
        public virtual DbSet<Currency_type> Currency_type { get; set; }
        public virtual DbSet<Tenders> Tenders { get; set; }
    }
}
