//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reestr_of_Contracts
    {
        public int ID { get; set; }
        public Nullable<int> Object_encryption { get; set; }
        public string Stage { get; set; }
        public string Object_Name { get; set; }
        public string Current_jobe { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Managers { get; set; }
        public string Project_Manager { get; set; }
        public string Source { get; set; }
    }
}
