//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons_persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respons_persons()
        {
            this.ContractsPersons = new HashSet<ContractsPersons>();
            this.PersonsReesters = new HashSet<PersonsReesters>();
            this.TendersPersons = new HashSet<TendersPersons>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Person_stats { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Sub_Name { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<bool> Activity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractsPersons> ContractsPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonsReesters> PersonsReesters { get; set; }
        public virtual PersonStats PersonStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TendersPersons> TendersPersons { get; set; }
    }
}
