//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons_persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respons_persons()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Main_Reestr = new HashSet<Main_Reestr>();
            this.Tenders = new HashSet<Tenders>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Person_stats { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Sub_Name { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<bool> Activity { get; set; }
    
        public virtual PersonStats PersonStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Main_Reestr> Main_Reestr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenders> Tenders { get; set; }
    }
}
