//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenders()
        {
            this.Respons_persons = new HashSet<Respons_persons>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDKey { get; set; }
        public Nullable<System.DateTime> Date_purchase { get; set; }
        public Nullable<System.DateTime> final__proposal_date { get; set; }
        public Nullable<System.DateTime> trading_date { get; set; }
        public string Object_name { get; set; }
        public string subject_of_a_contract { get; set; }
        public Nullable<decimal> starting_price { get; set; }
        public Nullable<decimal> price_date_submission { get; set; }
        public Nullable<decimal> price_inclusive_reduction { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Acceptance_date { get; set; }
        public Nullable<System.DateTime> Term_of_the_contract { get; set; }
        public string Repository { get; set; }
        public string Tender_number { get; set; }
        public Nullable<decimal> final_price { get; set; }
        public Nullable<int> ID_currency { get; set; }
        public Nullable<decimal> currency_rate { get; set; }
    
        public virtual Currency_type Currency_type { get; set; }
        public virtual Main_Reestr Main_Reestr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respons_persons> Respons_persons { get; set; }
    }
}
