//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TendersPersons
    {
        public Nullable<int> TenderID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int ID { get; set; }
    
        public virtual Respons_persons Respons_persons { get; set; }
        public virtual Tenders Tenders { get; set; }
    }
}
