//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp1.Model.AppDBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTN
    {
        public int id { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string Act_number { get; set; }
        public Nullable<System.DateTime> Date_of_accept { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> Date_of_contract { get; set; }
        public Nullable<double> Value_with_NDS { get; set; }
        public Nullable<System.DateTime> Date_of_invoice_ESF { get; set; }
        public Nullable<double> with_general_contractor { get; set; }
        public Nullable<double> with_subcontractors { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
